tools::Rd2latex("bssAlphaFit.Rd")
tools::Rd2latex("estimateAccumulatedVolatility.Rd")
tools::Rd2latex("gammaKernelBSS.Rd")
tools::Rd2latex("gammaKernelBSSFit.Rd")
tools::Rd2latex("gammaKernelCorrelation.Rd"	)
tools::Rd2latex("gammaKernelTau.Rd")
tools::Rd2latex("gammaKernelTauAsymptotic.Rd"	)
tools::Rd2latex("hybridSchemeCovarianceMatrix.Rd"	)
tools::Rd2latex("powerKernelBSS.Rd"	)
tools::Rd2latex("powerKernelBSSFit.Rd")
tools::Rd2latex("powerKernelCorrelation.Rd"	)
tools::Rd2latex("powerKernelTau.Rd")
tools::Rd2latex("realisedPowerVariation.Rd")
tools::Rd2latex("tauNonParametricEstimate.Rd")
